const $=id=>document.getElementById(id);
const screens=[...document.querySelectorAll('.screen')];
const params=new URLSearchParams(location.search);
const game=params.get('game')||'sudoku';
const DATA=window.MB_DATA;
const WE=window.WordEngine;
const META={
  cultura:{title:'Cultura exprés',badge:'✦',description:'Preguntes variades, clares i diferents cada dia.',label:'CULTURA',max:5},
  lletres:{title:'Lletres en ordre',badge:'Aa',description:'Completa cada frase ordenant les lletres de la paraula que falta.',label:'PARAULES',max:5},
  quadrat:{title:'Quadrat matemàtic',badge:'∑',description:'Col·loca tots els números perquè les files, columnes i diagonals sumin el resultat indicat.',label:'LÒGICA',max:5},
  sudoku:{title:'Sudoku',badge:'9',description:'Completa la graella sense repetir cap número a files, columnes ni blocs.',label:'SUDOKU',max:5},
  emparaulats:{title:'Emparaulats',badge:'ABC',description:'Construeix paraules en català, aprofita les caselles especials i supera el rival.',label:'EMPARAULATS',max:2}
};
const meta=META[game]||META.sudoku;
let difficulty='normal',mode='solo',socket=null,myId=null,roomCode=null,roomPlayers=[],creatorId=null,currentSeed='',startedAt=0,score=0,challenge=null,challengeIndex=0,mistakes=0,hints=0,selectedCell=null,botResult=null,wordState=null,pendingWord=[],selectedRackIndex=null,localWord=null;

function show(id){screens.forEach(screen=>screen.classList.toggle('active',screen.id===id));window.scrollTo({top:0,behavior:'instant'})}
function notify(message){const toast=$('toast');toast.textContent=message;toast.classList.add('show');clearTimeout(notify.timer);notify.timer=setTimeout(()=>toast.classList.remove('show'),1900)}
function send(type,payload={}){if(!socket||socket.readyState!==WebSocket.OPEN){notify('No hi ha connexió');return false}socket.send(JSON.stringify({type,...payload}));return true}
function playerName(){return $('playerName').value.trim()||'Jugador'}
function dateKey(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Madrid'}).format(new Date())}
function hash(text){let value=2166136261;for(const char of String(text)){value^=char.charCodeAt(0);value=Math.imul(value,16777619)}return value>>>0}
function rng(seed){let value=hash(seed)||1;return()=>{value+=0x6D2B79F5;let t=value;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function shuffled(values,random){const result=[...values];for(let i=result.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[result[i],result[j]]=[result[j],result[i]]}return result}
function dailyRotation(values,count,key){const ordered=shuffled(values,rng(`rotation-${key}`)),stamp=currentSeed.slice(0,10),day=Math.floor(Date.parse(`${stamp}T00:00:00Z`)/86400000),start=((day*count)%ordered.length+ordered.length)%ordered.length;return Array.from({length:Math.min(count,ordered.length)},(_,index)=>ordered[(start+index)%ordered.length])}
function setScore(value){score=value;$('liveScore').textContent=score}
function setFeedback(text,type=''){$('gameFeedback').textContent=text;$('gameFeedback').className=`feedback ${type}`}
function updateProgress(done,total){$('playProgress').textContent=`${Math.min(done,total)}/${total}`;if(mode==='room')send('arcade_progress',{done,total,score})}
function saveName(){localStorage.setItem('musicBattleName',playerName())}

function setup(){
  document.title=`${meta.title} · Music Battle`;$('gameTitle').textContent=meta.title;$('gameBadge').textContent=meta.badge;$('gameDescription').textContent=meta.description;$('roomLimitLabel').textContent=game==='emparaulats'?'Per a 2 persones':'Per a 2–5 persones';$('playerName').value=localStorage.getItem('musicBattleName')||'';
  $('difficultyChoices').querySelectorAll('button').forEach(button=>button.addEventListener('click',()=>{difficulty=button.dataset.level;$('difficultyChoices').querySelectorAll('button').forEach(item=>item.classList.toggle('selected',item===button))}));
  $('playBot').onclick=()=>{saveName();mode='solo';startLocal()};
  $('createRoom').onclick=()=>{if(!$('playerName').value.trim())return notify('Escriu el teu nom');saveName();mode='room';send('arcade_create',{game,difficulty,playerName:playerName()})};
  $('joinRoom').onclick=()=>{if(!$('playerName').value.trim())return notify('Escriu el teu nom');const code=prompt('Codi de la sala:');if(!code)return;saveName();mode='room';send('arcade_join',{roomCode:code,playerName:playerName()})};
  $('copyRoomCode').onclick=()=>navigator.clipboard?.writeText(roomCode).then(()=>notify('Codi copiat')).catch(()=>notify(roomCode));
  $('leaveRoom').onclick=leaveArcadeRoom;$('quitGame').onclick=()=>{if(confirm('Vols sortir de la partida?'))leaveArcadeRoom()};
  $('startRoom').onclick=()=>send('arcade_start');$('playAgain').onclick=()=>location.reload();
  if(params.get('quick')==='1'){difficulty='normal';setTimeout(()=>$('playBot').click(),180)}
}

function connect(){
  const url=`${location.protocol==='https:'?'wss':'ws'}://${location.host}`;socket=new WebSocket(url);
  socket.onopen=()=>{$('connectionStatus').textContent='Connectat al servidor';const id=sessionStorage.getItem('arcadePlayerId'),code=sessionStorage.getItem('arcadeRoomCode');if(id&&code)send('arcade_resume',{playerId:id,roomCode:code})};
  socket.onclose=()=>{$('connectionStatus').textContent='Reconnectant...';setTimeout(connect,900)};
  socket.onmessage=event=>handleSocket(JSON.parse(event.data));
}

function handleSocket(data){
  switch(data.type){
    case 'connected':if(!myId)myId=data.playerId;break;
    case 'arcade_created':case 'arcade_joined':roomCode=data.roomCode;sessionStorage.setItem('arcadePlayerId',myId);sessionStorage.setItem('arcadeRoomCode',roomCode);show('roomScreen');break;
    case 'arcade_resumed':myId=data.playerId;roomCode=data.roomCode;show(data.phase==='lobby'?'roomScreen':'playScreen');break;
    case 'arcade_resume_failed':sessionStorage.removeItem('arcadePlayerId');sessionStorage.removeItem('arcadeRoomCode');break;
    case 'arcade_state':renderRoom(data);break;
    case 'arcade_challenge_started':currentSeed=data.seed;startChallenge(data.seed);break;
    case 'arcade_progress_state':renderOpponents(data.players);break;
    case 'arcade_results':renderResults(data.players);break;
    case 'arcade_word_state':startOrUpdateOnlineWord(data);break;
    case 'arcade_word_error':notify(data.message);break;
    case 'arcade_left':clearRoom();show('setupScreen');break;
    case 'arcade_player_left':notify('Un jugador ha sortit');break;
    case 'error':notify(data.message);break;
  }
}

function renderRoom(data){
  roomCode=data.roomCode;roomPlayers=data.players;creatorId=data.creatorId;difficulty=data.difficulty||difficulty;$('roomCode').textContent=roomCode;$('roomGameLabel').textContent=`${meta.title} · ${difficultyLabel(difficulty)}`;
  $('roomPlayers').innerHTML=roomPlayers.map(player=>`<div class="room-player ${player.id===myId?'me':''}"><b>${escapeHtml(player.name)}</b><small>${player.id===creatorId?'Creador':player.connected?'Connectat':'Reconnectant'}</small></div>`).join('');
  const ready=roomPlayers.length>=2,isCreator=myId===creatorId;$('startRoom').hidden=!isCreator;$('startRoom').disabled=!ready;$('startRoom').textContent=ready?'Començar partida':'Falta un jugador';$('roomMessage').textContent=ready?(isCreator?'Ja podeu començar':`Esperant que ${roomPlayers[0].name} comenci...`):`Comparteix el codi. Hi caben ${meta.max} jugadors.`;if(data.phase==='lobby')show('roomScreen');else renderOpponents(roomPlayers);
}
function renderOpponents(values){roomPlayers=values;$('opponentStrip').innerHTML=values.filter(player=>player.id!==myId).map(player=>`<span class="opponent-chip ${player.done?'done':''}">${escapeHtml(player.name)} · ${player.done?'acabat':`${player.progress||0}/${player.total||'?'}`}</span>`).join('')}
function leaveArcadeRoom(){if(mode==='room')send('arcade_leave');clearRoom();location.href='https://quiz-battle-jordi.jvinola4.chatgpt.site/'}
function clearRoom(){sessionStorage.removeItem('arcadePlayerId');sessionStorage.removeItem('arcadeRoomCode');roomCode=null}
function difficultyLabel(value){return value==='easy'?'Fàcil':value==='hard'?'Difícil':'Mitjà'}
function escapeHtml(value){return String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}

function startLocal(){currentSeed=`${dateKey()}-${game}-${difficulty}`;startChallenge(currentSeed)}
function startChallenge(seed){
  startedAt=Date.now();setScore(0);mistakes=0;hints=0;challengeIndex=0;$('playGameLabel').textContent=`${meta.label} · ${difficultyLabel(difficulty).toUpperCase()}`;show('playScreen');setFeedback('');
  if(game==='emparaulats')return startLocalWord(seed);
  challenge=createChallenge(seed);botResult=mode==='solo'?makeBotResult(seed,challenge):null;renderOpponents(mode==='solo'?[{id:'bot',name:'Màquina',progress:0,total:challenge.total,done:false}]:roomPlayers);renderCurrentChallenge();
}

function createChallenge(seed){const random=rng(seed);if(game==='cultura'){const count=difficulty==='easy'?8:difficulty==='hard'?12:10;return{type:game,items:dailyRotation(DATA.culture,count,`${game}-${difficulty}`),total:count}}if(game==='lletres'){const count=difficulty==='easy'?5:difficulty==='hard'?8:6;const pool=DATA.phrases.filter(item=>difficulty==='easy'?item.answer.length<=7:difficulty==='hard'?item.answer.length>=6:true);return{type:game,items:dailyRotation(pool,count,`${game}-${difficulty}`),total:count,random}}if(game==='quadrat')return createMath(random);return createSudoku(random)}
function makeBotResult(seed,value){
  const random=rng(`${seed}-bot`);
  const factor=difficulty==='easy'?1.22:(difficulty==='hard'?0.82:1);
  const expected={cultura:value.total*6500,lletres:value.total*9000,quadrat:85000,sudoku:difficulty==='easy'?150000:(difficulty==='hard'?330000:230000)}[game]||120000;
  const accuracy=difficulty==='easy'?0.72:(difficulty==='hard'?0.93:0.84);
  return{name:'Màquina',elapsedMs:Math.round(expected*factor*(.85+random()*.3)),score:Math.round((game==='cultura'?value.total*1000:game==='lletres'?value.total*1200:9000)*accuracy),done:false};
}

function renderCurrentChallenge(){if(game==='cultura')renderCulture();else if(game==='lletres')renderLetters();else if(game==='quadrat')renderMath();else renderSudoku()}
function finishChallenge(){const elapsedMs=Date.now()-startedAt;if(mode==='room'){setFeedback('Has acabat. Esperant els altres jugadors...','good');$('gameMount').innerHTML=`<div class="challenge-title"><h2>Repte completat!</h2><p>Resultat enviat a la sala.</p></div>`;send('arcade_submit',{score,elapsedMs,mistakes,hints});return}botResult.done=true;const mine={id:myId||'me',name:playerName(),score,elapsedMs,done:true};renderResults([mine,{id:'bot',...botResult}])}

function renderCulture(){
  const item=challenge.items[challengeIndex];
  if(!item)return finishChallenge();
  updateProgress(challengeIndex+1,challenge.total);
  $('gameMount').innerHTML=`<h2 class="culture-question">${escapeHtml(item.question)}</h2><div class="culture-options">${item.options.map((option,index)=>`<button data-index="${index}">${escapeHtml(option)}</button>`).join('')}</div>`;
  const questionAt=Date.now();
  document.querySelectorAll('.culture-options button').forEach(button=>{
    button.onclick=()=>{
      document.querySelectorAll('.culture-options button').forEach(option=>option.disabled=true);
      const index=Number(button.dataset.index),correct=index===item.answer;
      button.classList.add(correct?'correct':'wrong');
      document.querySelector(`.culture-options button[data-index="${item.answer}"]`).classList.add('correct');
      if(correct){const gain=Math.max(300,1000-Math.floor((Date.now()-questionAt)/20));setScore(score+gain);setFeedback(`Correcte! +${gain} punts`,'good')}
      else{mistakes++;setFeedback('No era aquesta.','bad')}
      challengeIndex++;
      setTimeout(renderCulture,850);
    };
  });
}

function renderLetters(){const item=challenge.items[challengeIndex];if(!item)return finishChallenge();updateProgress(challengeIndex+1,challenge.total);const random=rng(`${currentSeed}-${challengeIndex}`),letters=shuffled([...item.answer.toLocaleUpperCase('ca')],random);challenge.currentLetters=letters;challenge.letterAnswer=[];$('gameMount').innerHTML=`<h2 class="challenge-title">Completa la frase</h2><div class="letters-clue">${escapeHtml(item.sentence).replace('___','<b>________</b>')}</div><div class="answer-slots" id="answerSlots">${letters.map(()=>'<span class="answer-slot"></span>').join('')}</div><div class="letter-bank">${letters.map((letter,index)=>`<button class="letter-tile" data-index="${index}">${escapeHtml(letter)}</button>`).join('')}</div><div class="action-row"><button id="clearLetters">Esborrar</button><button id="hintLetters">Pista</button><button id="checkLetters" class="primary">Comprovar</button></div>`;document.querySelectorAll('.letter-tile').forEach(button=>button.onclick=()=>{if(button.classList.contains('used'))return;challenge.letterAnswer.push({letter:button.textContent,index:Number(button.dataset.index)});button.classList.add('used');paintLetterAnswer()});$('clearLetters').onclick=()=>{challenge.letterAnswer=[];document.querySelectorAll('.letter-tile').forEach(button=>button.classList.remove('used'));paintLetterAnswer()};$('hintLetters').onclick=()=>{const next=item.answer.toLocaleUpperCase('ca')[challenge.letterAnswer.length];const tile=[...document.querySelectorAll('.letter-tile')].find(button=>!button.classList.contains('used')&&button.textContent===next);if(tile){hints++;tile.click();setScore(Math.max(0,score-40));setFeedback('Pista: hem col·locat la lletra següent.')}};$('checkLetters').onclick=()=>{const answer=challenge.letterAnswer.map(value=>value.letter).join('').toLocaleLowerCase('ca');if(answer===item.answer.toLocaleLowerCase('ca')){const gain=Math.max(350,1200-hints*60);setScore(score+gain);setFeedback(`Molt bé! +${gain} punts`,'good');challengeIndex++;setTimeout(renderLetters,650)}else{mistakes++;setFeedback('Encara no lliga. Revisa l’ordre.','bad')}}}
function paintLetterAnswer(){document.querySelectorAll('.answer-slot').forEach((slot,index)=>{slot.textContent=challenge.letterAnswer[index]?.letter||'';slot.classList.toggle('filled',Boolean(slot.textContent));slot.onclick=()=>{if(!challenge.letterAnswer[index])return;const removed=challenge.letterAnswer.splice(index,1)[0];document.querySelector(`.letter-tile[data-index="${removed.index}"]`).classList.remove('used');paintLetterAnswer()}})}

function createMath(random){const base=[8,1,6,3,5,7,4,9,2],factor=1+Math.floor(random()*3),offset=Math.floor(random()*9);let values=base.map(n=>n*factor+offset);const transforms=[v=>v,v=>[v[6],v[3],v[0],v[7],v[4],v[1],v[8],v[5],v[2]],v=>[...v].reverse(),v=>[v[2],v[5],v[8],v[1],v[4],v[7],v[0],v[3],v[6]]];values=transforms[Math.floor(random()*transforms.length)](values);const fixedCount=difficulty==='easy'?4:difficulty==='hard'?1:2,fixed=new Set(shuffled([...Array(9).keys()],random).slice(0,fixedCount));const rows=[0,1,2].map(r=>values.slice(r*3,r*3+3).reduce((a,b)=>a+b,0)),cols=[0,1,2].map(c=>values[c]+values[c+3]+values[c+6]),diags=[values[0]+values[4]+values[8],values[2]+values[4]+values[6]];return{type:'quadrat',solution:values,cells:values.map((value,index)=>fixed.has(index)?value:null),fixed,rows,cols,diags,total:1,bank:shuffled(values.filter((_,index)=>!fixed.has(index)),random)}}
function renderMath(){updateProgress(1,1);$('gameMount').innerHTML=`<h2 class="challenge-title">Fes quadrar totes les sumes</h2><p class="challenge-help">Toca una casella i després el número que hi vols posar.</p><div class="math-wrap"><div class="math-grid">${challenge.cells.map((value,index)=>`<button class="math-cell ${challenge.fixed.has(index)?'fixed':''}" data-cell="${index}">${value??''}</button>`).join('')}</div><div class="math-targets">${challenge.rows.map((value,i)=>`<div class="target-row">Fila ${i+1}: <b>${value}</b></div>`).join('')}${challenge.cols.map((value,i)=>`<div class="target-row">Col. ${i+1}: <b>${value}</b></div>`).join('')}<div class="target-row">Diagonal ↘: <b>${challenge.diags[0]}</b></div><div class="target-row">Diagonal ↙: <b>${challenge.diags[1]}</b></div></div></div><div class="number-bank">${challenge.bank.map((value,index)=>`<button class="number-tile" data-bank="${index}">${value}</button>`).join('')}</div><div class="action-row"><button id="clearMath">Netejar</button><button id="hintMath">Pista</button><button id="checkMath" class="primary">Comprovar</button></div>`;document.querySelectorAll('.math-cell:not(.fixed)').forEach(cell=>cell.onclick=()=>{selectedCell=Number(cell.dataset.cell);document.querySelectorAll('.math-cell').forEach(item=>item.classList.toggle('selected',item===cell))});document.querySelectorAll('.number-tile').forEach(tile=>tile.onclick=()=>placeMathNumber(Number(tile.dataset.bank)));$('clearMath').onclick=()=>{challenge.cells=challenge.cells.map((value,index)=>challenge.fixed.has(index)?value:null);challenge.bank=challenge.solution.filter((_,index)=>!challenge.fixed.has(index));renderMath()};$('hintMath').onclick=()=>{const index=challenge.cells.findIndex((value,i)=>!challenge.fixed.has(i)&&value!==challenge.solution[i]);if(index<0)return;const wanted=challenge.solution[index],bankIndex=challenge.bank.indexOf(wanted);if(challenge.cells[index]!=null)challenge.bank.push(challenge.cells[index]);challenge.cells[index]=wanted;if(bankIndex>=0)challenge.bank.splice(bankIndex,1);hints++;setScore(Math.max(0,score-100));renderMath();setFeedback('Hem col·locat un número correcte.','good')};$('checkMath').onclick=()=>{if(challenge.cells.some(value=>value==null))return setFeedback('Encara falten números.','bad');if(challenge.cells.every((value,index)=>value===challenge.solution[index])){setScore(score+Math.max(1000,9000-(Date.now()-startedAt)/30-hints*250|0));finishChallenge()}else{mistakes++;setFeedback('Alguna suma no quadra. Torna-ho a mirar.','bad')}}}
function placeMathNumber(bankIndex){if(selectedCell==null||challenge.fixed.has(selectedCell))return notify('Primer toca una casella buida');const value=challenge.bank[bankIndex];if(challenge.cells[selectedCell]!=null)challenge.bank.push(challenge.cells[selectedCell]);challenge.cells[selectedCell]=value;challenge.bank.splice(bankIndex,1);selectedCell=null;renderMath()}

function createSudoku(random){const base=3,side=9,pattern=(r,c)=>(base*(r%base)+Math.floor(r/base)+c)%side;const rows=shuffled([0,1,2],random).flatMap(group=>shuffled([0,1,2],random).map(row=>group*3+row));const cols=shuffled([0,1,2],random).flatMap(group=>shuffled([0,1,2],random).map(col=>group*3+col));const nums=shuffled([1,2,3,4,5,6,7,8,9],random),solution=rows.flatMap(r=>cols.map(c=>nums[pattern(r,c)]));const clues=difficulty==='easy'?42:difficulty==='hard'?27:34,visible=new Set(shuffled([...Array(81).keys()],random).slice(0,clues));return{type:'sudoku',solution,cells:solution.map((value,index)=>visible.has(index)?value:null),fixed:visible,total:1}}
function renderSudoku(){updateProgress(1,1);$('gameMount').innerHTML=`<h2 class="challenge-title">Completa el Sudoku</h2><div class="sudoku-board">${challenge.cells.map((value,index)=>`<button class="sudoku-cell ${challenge.fixed.has(index)?'fixed':''} ${Math.floor(index/9)%3===2&&index<72?'block-bottom':''}" data-cell="${index}">${value??''}</button>`).join('')}</div><div class="digit-bank">${[1,2,3,4,5,6,7,8,9].map(n=>`<button data-digit="${n}">${n}</button>`).join('')}</div><div class="action-row"><button id="eraseSudoku">Esborrar</button><button id="hintSudoku">Pista</button><button id="checkSudoku" class="primary">Comprovar</button></div>`;document.querySelectorAll('.sudoku-cell:not(.fixed)').forEach(cell=>cell.onclick=()=>selectSudoku(Number(cell.dataset.cell)));document.querySelectorAll('[data-digit]').forEach(button=>button.onclick=()=>putSudoku(Number(button.dataset.digit)));$('eraseSudoku').onclick=()=>putSudoku(null);$('hintSudoku').onclick=()=>{let index=selectedCell;if(index==null||challenge.fixed.has(index)||challenge.cells[index]===challenge.solution[index])index=challenge.cells.findIndex((value,i)=>!challenge.fixed.has(i)&&value!==challenge.solution[i]);if(index<0)return;challenge.cells[index]=challenge.solution[index];hints++;setScore(Math.max(0,score-150));renderSudoku();selectSudoku(index)};$('checkSudoku').onclick=()=>{let errors=0;challenge.cells.forEach((value,index)=>{const cell=document.querySelector(`.sudoku-cell[data-cell="${index}"]`);const wrong=value!=null&&value!==challenge.solution[index];cell?.classList.toggle('error',wrong);if(wrong)errors++});if(challenge.cells.some(value=>value==null))return setFeedback(errors?`Hi ha ${errors} número${errors>1?'s':''} incorrecte${errors>1?'s':''} i encara falten caselles.`:'Encara falten caselles.','bad');if(!errors){setScore(score+Math.max(1200,10000-(Date.now()-startedAt)/45-hints*300|0));finishChallenge()}else{mistakes+=errors;setFeedback(`Revisa ${errors} casella${errors>1?'s':''}.`,'bad')}}}
function selectSudoku(index){selectedCell=index;const r=Math.floor(index/9),c=index%9;document.querySelectorAll('.sudoku-cell').forEach(cell=>{const i=Number(cell.dataset.cell),rr=Math.floor(i/9),cc=i%9;cell.classList.toggle('selected',i===index);cell.classList.toggle('peer',i!==index&&(rr===r||cc===c||(Math.floor(rr/3)===Math.floor(r/3)&&Math.floor(cc/3)===Math.floor(c/3))))})}
function putSudoku(value){if(selectedCell==null||challenge.fixed.has(selectedCell))return notify('Toca una casella buida');challenge.cells[selectedCell]=value;const cell=document.querySelector(`.sudoku-cell[data-cell="${selectedCell}"]`);cell.textContent=value??'';cell.classList.remove('error')}

function startLocalWord(seed){const random=rng(seed);const bag=WE.buildBag(random);localWord={board:WE.emptyBoard(),bag,racks:[WE.draw(bag,7),WE.draw(bag,7)],scores:[0,0],turn:0,turns:0,passes:0,random};wordState={local:true};renderWordState()}
function startOrUpdateOnlineWord(data){mode='room';wordState=data;roomPlayers=data.players;show('playScreen');$('playGameLabel').textContent=`EMPARAULATS · ${difficultyLabel(data.difficulty).toUpperCase()}`;setScore(data.players.find(player=>player.id===myId)?.score||0);pendingWord=[];selectedRackIndex=null;renderWordState()}
function currentWordView(){if(mode==='solo')return{board:localWord.board,rack:localWord.racks[0],players:[{id:'me',name:playerName(),score:localWord.scores[0]},{id:'bot',name:'Màquina',score:localWord.scores[1]}],turnId:localWord.turn===0?'me':'bot',bagCount:localWord.bag.length,round:localWord.turns};return wordState}
function renderWordState(){const view=currentWordView(),myTurn=view.turnId===(mode==='solo'?'me':myId),rack=view.rack||[];$('playProgress').textContent=`Torn ${Math.floor((view.round||0)/Math.max(1,view.players.length))+1}`;renderOpponents(view.players.map(player=>({...player,progress:player.score,total:'pts'})));$('gameMount').innerHTML=`<div class="word-layout"><div><div class="word-board">${view.board.flatMap((row,r)=>row.map((letter,c)=>{const premium=WE.premiumAt(r,c),label={tw:'TP',dw:'DP',tl:'TL',dl:'DL',center:'★'}[premium]||'';return`<button class="word-cell ${premium}" data-r="${r}" data-c="${c}">${letter?`${letter}<small class="tile-points">${WE.POINTS[letter]||1}</small>`:`<span class="bonus">${label}</span>`}</button>`})).join('')}</div><div class="rack">${rack.map((letter,index)=>`<button class="rack-tile" data-rack="${index}" ${myTurn?'':'disabled'}>${letter}<small>${WE.POINTS[letter]||1}</small></button>`).join('')}</div></div><aside class="word-side"><div class="turn-box"><small>TORN</small><b>${escapeHtml(view.players.find(p=>p.id===view.turnId)?.name||'Màquina')}</b><small>${view.bagCount} fitxes a la bossa</small></div><div class="word-scores">${view.players.map(player=>`<div class="word-score ${player.id===view.turnId?'turn':''}"><span>${escapeHtml(player.name)}</span><b>${player.score}</b></div>`).join('')}</div><div class="word-actions"><button id="wordClear" type="button">Netejar</button><button id="wordHint" type="button">Pista</button><button id="wordPass" type="button" ${myTurn?'':'disabled'}>Canviar</button><button id="wordPlay" class="primary" type="button" ${myTurn?'':'disabled'}>Jugar paraula</button></div></aside></div>`;paintPendingWord();document.querySelectorAll('.rack-tile').forEach(tile=>tile.onclick=()=>{selectedRackIndex=Number(tile.dataset.rack);document.querySelectorAll('.rack-tile').forEach(item=>item.classList.toggle('selected',item===tile))});document.querySelectorAll('.word-cell').forEach(cell=>cell.onclick=()=>placeWordTile(Number(cell.dataset.r),Number(cell.dataset.c)));$('wordClear').onclick=()=>{pendingWord=[];selectedRackIndex=null;paintPendingWord()};$('wordHint').onclick=wordHint;$('wordPass').onclick=passWord;$('wordPlay').onclick=playWord;if(mode==='solo'&&localWord.turn===1)setTimeout(playBotWord,250)}
function placeWordTile(r,c){const view=currentWordView();if(view.turnId!==(mode==='solo'?'me':myId))return;if(view.board[r][c])return notify('Aquesta casella ja està ocupada');const existing=pendingWord.findIndex(p=>p.r===r&&p.c===c);if(existing>=0){pendingWord.splice(existing,1);paintPendingWord();return}if(selectedRackIndex==null)return notify('Primer toca una fitxa');if(pendingWord.some(p=>p.rackIndex===selectedRackIndex))return;pendingWord.push({r,c,letter:view.rack[selectedRackIndex],rackIndex:selectedRackIndex});selectedRackIndex=null;paintPendingWord()}
function paintPendingWord(){document.querySelectorAll('.word-cell').forEach(cell=>{const p=pendingWord.find(item=>item.r===Number(cell.dataset.r)&&item.c===Number(cell.dataset.c));cell.classList.toggle('pending',Boolean(p));if(p)cell.innerHTML=`${p.letter}<small class="tile-points">${WE.POINTS[p.letter]||1}</small>`});document.querySelectorAll('.rack-tile').forEach(tile=>{const used=pendingWord.some(p=>p.rackIndex===Number(tile.dataset.rack));tile.style.opacity=used?'.25':'1';tile.classList.toggle('selected',Number(tile.dataset.rack)===selectedRackIndex)})}
function playWord(){const view=currentWordView(),dictionary=new Set(DATA.words.map(WE.normalize)),result=WE.validateMove(view.board,pendingWord,dictionary);if(!result.ok)return setFeedback(result.message,'bad');if(mode==='room'){send('arcade_word_move',{placements:pendingWord});pendingWord=[];return}localWord.board=WE.applyMove(localWord.board,result.placements);const used=[...pendingWord].sort((a,b)=>b.rackIndex-a.rackIndex);used.forEach(p=>localWord.racks[0].splice(p.rackIndex,1));localWord.racks[0].push(...WE.draw(localWord.bag,7-localWord.racks[0].length));localWord.scores[0]+=result.score;localWord.turn=1;localWord.turns++;localWord.passes=0;setScore(localWord.scores[0]);pendingWord=[];setFeedback(`${result.words.join(' · ')}: +${result.score} punts`,'good');if(shouldFinishWords())return finishLocalWords();renderWordState()}
function passWord(){if(mode==='room')return send('arcade_word_pass');exchangeLocalRack(0);localWord.turn=1;localWord.turns++;localWord.passes++;pendingWord=[];if(shouldFinishWords())return finishLocalWords();renderWordState()}
function exchangeLocalRack(index){if(!localWord.bag.length)return;const old=localWord.racks[index],replacement=WE.draw(localWord.bag,Math.min(7,localWord.bag.length));localWord.bag.push(...old);for(let i=localWord.bag.length-1;i>0;i--){const j=Math.floor(localWord.random()*(i+1));[localWord.bag[i],localWord.bag[j]]=[localWord.bag[j],localWord.bag[i]]}localWord.racks[index]=replacement}
function wordHint(){const view=currentWordView(),move=WE.chooseAiMove(view.board,view.rack,new Set(DATA.words.map(WE.normalize)),difficulty,rng(`${currentSeed}-hint-${hints}`));hints++;if(!move)return setFeedback('Ara mateix no trobo cap jugada; pots passar.');const first=move.placements[0],horizontal=move.placements.every(p=>p.r===first.r);setFeedback(`Pista: ${move.word.length} lletres, comença per ${move.word[0]}, ${horizontal?'horitzontal':'vertical'}, prop de fila ${first.r+1}.`)}
function playBotWord(){if(localWord.turn!==1)return;const move=WE.chooseAiMove(localWord.board,localWord.racks[1],new Set(DATA.words.map(WE.normalize)),difficulty,localWord.random);if(move){localWord.board=WE.applyMove(localWord.board,move.placements);const remaining=[...localWord.racks[1]];for(const p of move.placements){const index=remaining.indexOf(p.letter);if(index>=0)remaining.splice(index,1)}localWord.racks[1]=remaining;localWord.racks[1].push(...WE.draw(localWord.bag,7-remaining.length));localWord.scores[1]+=move.score;localWord.passes=0;setFeedback(`La màquina juga ${move.word.toLocaleLowerCase('ca')} (+${move.score}).`)}else{exchangeLocalRack(1);localWord.passes++;setFeedback('La màquina canvia les fitxes.')}localWord.turn=0;localWord.turns++;if(shouldFinishWords())return finishLocalWords();renderWordState()}
function shouldFinishWords(){return localWord.turns>=16||localWord.passes>=4||(!localWord.bag.length&&localWord.racks.some(rack=>!rack.length))}
function finishLocalWords(){const elapsedMs=Date.now()-startedAt;renderResults([{id:'me',name:playerName(),score:localWord.scores[0],elapsedMs,done:true},{id:'bot',name:'Màquina',score:localWord.scores[1],elapsedMs,done:true}])}

function renderResults(values){const sorted=[...values].sort((a,b)=>b.score-a.score||a.elapsedMs-b.elapsedMs),mine=sorted.find(player=>player.id===myId)||sorted.find(player=>player.id==='me')||sorted[0],winner=sorted[0],won=winner.id===mine.id;recordStats(won,mine.score);show('resultsScreen');$('resultIcon').textContent=won?'★':'✓';$('resultTitle').textContent=won?(sorted[1]&&winner.score===sorted[1].score?'Empat!':'Has guanyat!'):`Guanya ${winner.name}`;$('resultSummary').textContent=`${mine.score} punts · ${formatTime(mine.elapsedMs)}`;$('resultRanking').innerHTML=sorted.map((player,index)=>`<div class="rank-row ${index===0?'winner':''}"><span class="place">${index+1}</span><span><b>${escapeHtml(player.name)}</b><small>${formatTime(player.elapsedMs)}</small></span><strong>${player.score} pts</strong></div>`).join('');clearRoom()}
function recordStats(won,points){let stats={games:0,wins:0,points:0};try{stats={...stats,...JSON.parse(localStorage.getItem('musicBattleStats')||'{}')}}catch{}stats.games+=1;if(won)stats.wins+=1;stats.points+=Number(points)||0;localStorage.setItem('musicBattleStats',JSON.stringify(stats))}
function formatTime(ms){if(!Number.isFinite(ms))return '—';const seconds=Math.round(ms/1000);return seconds<60?`${seconds} s`:`${Math.floor(seconds/60)} min ${seconds%60} s`}

setup();connect();
