(function(){
const culture=[
['Quina és la capital de Portugal?',['Lisboa','Porto','Coïmbra','Braga'],0],
['Quin planeta és conegut com el planeta vermell?',['Venus','Mart','Júpiter','Mercuri'],1],
['Qui va pintar La nit estelada?',['Picasso','Dalí','Van Gogh','Miró'],2],
['Quants costats té un hexàgon?',['5','6','7','8'],1],
['Quin és l’oceà més gran?',['Atlàntic','Índic','Àrtic','Pacífic'],3],
['En quin continent es troba el Perú?',['Àsia','Amèrica del Sud','Àfrica','Europa'],1],
['Quin animal és el més gran del planeta?',['Elefant africà','Balena blava','Girafa','Tauró blanc'],1],
['Qui va escriure Don Quixot?',['Miguel de Cervantes','Federico García Lorca','Lope de Vega','Quevedo'],0],
['Quin element químic té el símbol O?',['Or','Oxigen','Osmí','Ozó'],1],
['Quina llengua es parla principalment al Brasil?',['Castellà','Portuguès','Francès','Italià'],1],
['Quin és el satèl·lit natural de la Terra?',['Fobos','Europa','La Lluna','Tità'],2],
['Quants minuts té una hora i mitja?',['60','75','90','120'],2],
['Quin instrument té tecles blanques i negres?',['Violí','Piano','Flauta','Trompeta'],1],
['Quina ciutat és travessada pel riu Tàmesi?',['Dublín','Londres','Amsterdam','Berlín'],1],
['Com s’anomena el procés pel qual les plantes fabriquen aliment?',['Digestió','Fermentació','Fotosíntesi','Evaporació'],2],
['Quina muntanya és la més alta del món?',['K2','Everest','Mont Blanc','Kilimanjaro'],1],
['Quin esport es juga a Wimbledon?',['Golf','Tennis','Cricket','Rugbi'],1],
['Quants ossos té aproximadament un adult?',['106','206','306','406'],1],
['Quina és la moneda del Japó?',['Won','Yuan','Ien','Rupia'],2],
['Qui va compondre Les quatre estacions?',['Mozart','Beethoven','Vivaldi','Bach'],2],
['Quin gas absorbeixen les plantes?',['Oxigen','Diòxid de carboni','Heli','Hidrogen'],1],
['Quina és l’illa més gran de la Mediterrània?',['Mallorca','Sardenya','Sicília','Xipre'],2],
['En quin país hi ha les piràmides de Gizeh?',['Mèxic','Egipte','Grècia','Jordània'],1],
['Quin mamífer pot volar?',['Esquirol','Ratpenat','Pingüí','Ornitorrinc'],1],
['Quina és la capital d’Austràlia?',['Sydney','Melbourne','Canberra','Perth'],2],
['Quin nombre romà representa la X?',['5','10','50','100'],1],
['Quin òrgan bombeja la sang?',['Fetge','Pulmó','Cor','Ronyó'],2],
['Qui és l’autor d’El petit príncep?',['Jules Verne','Antoine de Saint-Exupéry','Victor Hugo','Albert Camus'],1],
['Quin mar banya la Costa Brava?',['Cantàbric','Mediterrani','Negre','Bàltic'],1],
['Quina figura té tots els punts a la mateixa distància del centre?',['Triangle','Rectangle','Cercle','Trapezi'],2],
['Quin és el metall principal de les llaunes de refresc?',['Ferro','Alumini','Coure','Plom'],1],
['Quina ciutat italiana té canals i góndoles?',['Roma','Venècia','Milà','Nàpols'],1],
['Quants jugadors té un equip de futbol al camp?',['9','10','11','12'],2],
['Quin científic va formular la teoria de la relativitat?',['Newton','Einstein','Darwin','Galileu'],1],
['Quin país té forma de bota?',['Croàcia','Itàlia','Grècia','Portugal'],1],
['Quina part de l’ordinador mostra la imatge?',['Teclat','Monitor','Ratolí','Micròfon'],1],
['Quin és el primer mes de l’any?',['Desembre','Gener','Febrer','Març'],1],
['Quin és l’animal terrestre més ràpid?',['Lleó','Guepard','Cavall','Antílop'],1],
['Quina capital europea té la Torre Eiffel?',['Roma','Brussel·les','París','Viena'],2],
['Quants graus té un angle recte?',['45','60','90','180'],2],
['Quin escriptor català va crear el personatge de Tirant lo Blanc?',['Joanot Martorell','Jacint Verdaguer','Àngel Guimerà','Mercè Rodoreda'],0],
['Quin riu passa per Girona?',['Ter','Segre','Ebre','Llobregat'],0],
['A quina comarca es troba Girona?',['Gironès','Selva','Empordà','Garrotxa'],0],
['Quin és el resultat de 12 per 8?',['84','92','96','108'],2],
['Quina capa protegeix la Terra de part de la radiació solar?',['Capa d’ozó','Escorça','Ionosfera','Magma'],0],
['Quin país va inventar els Jocs Olímpics antics?',['Itàlia','Grècia','Egipte','Turquia'],1],
['Quin color s’obté barrejant blau i groc?',['Taronja','Verd','Lila','Marró'],1],
['Quina és la capital de Catalunya?',['Girona','Tarragona','Barcelona','Lleida'],2],
['Quina ciència estudia els éssers vius?',['Geologia','Biologia','Astronomia','Física'],1],
['Quants dies té un any de traspàs?',['364','365','366','367'],2],
['Quin instrument serveix per mesurar la temperatura?',['Baròmetre','Termòmetre','Higròmetre','Cronòmetre'],1],
['Quin és el continent més petit?',['Europa','Oceania','Antàrtida','Amèrica'],1],
['Quin pintor català és conegut pels rellotges tous?',['Miró','Dalí','Tàpies','Fortuny'],1],
['Quina sang porta oxigen des dels pulmons?',['Arterial','Venosa','Limfa','Plasma'],0],
['Quina ciutat va acollir els Jocs Olímpics de 1992?',['Madrid','Barcelona','Sevilla','València'],1],
['Quin és el plural de “llapis” en català?',['Llapisos','Llapissos','Llapis','Llapiss'],2],
['Quina estació ve després de l’estiu?',['Primavera','Hivern','Tardor','Estiu'],2],
['Quin animal posa els ous més grans?',['Àguila','Estruç','Pingüí','Cigne'],1],
['Quina és la fórmula química de l’aigua?',['CO₂','O₂','H₂O','NaCl'],2],
['Quin país té Ottawa com a capital?',['Canadà','Estats Units','Austràlia','Irlanda'],0]
];

const phrases=[
['A l’estiu busquem ombra sota un gran ___.','arbre'],['Abans de sortir, tanca bé la ___.','porta'],['El tren arriba puntual a l’___.','estació'],['Per escriure a la pissarra fem servir un ___.','guix'],['Quan plou obrim el ___.','paraigua'],
['La sopa es menja amb una ___.','cullera'],['A la nit veiem la lluna i les ___.','estrelles'],['El peix viu dins de l’___.','aigua'],['Per saber l’hora mirem el ___.','rellotge'],['El mestre explica la lliçó a la ___.','classe'],
['La bicicleta té dues ___.','rodes'],['Guardem els llibres a la ___.','prestatgeria'],['El pa es cou dins del ___.','forn'],['Al bosc podem sentir cantar els ___.','ocells'],['Per travessar el riu passem pel ___.','pont'],
['La neu és freda i de color ___.','blanc'],['A la platja juguem amb la ___.','sorra'],['El metge treballa a l’___.','hospital'],['La primavera omple els camps de ___.','flors'],['Per tallar paper fem servir unes ___.','tisores'],
['La mel la fabriquen les ___.','abelles'],['El cotxe s’atura quan el semàfor és ___.','vermell'],['L’avió s’enlaira des de l’___.','aeroport'],['Per veure-hi millor encenem el ___.','llum'],['La gallina viu al ___.','galliner'],
['El dissabte forma part del cap de ___.','setmana'],['El gat persegueix un petit ___.','ratolí'],['A l’hivern ens posem un bon ___.','abric'],['La pilota ha entrat dins la ___.','porteria'],['Un llibre està format per moltes ___.','pàgines'],
['La fruita groga i allargada és el ___.','plàtan'],['Quan tenim set bevem un got d’___.','aigua'],['El sol surt cada dia per l’___.','est'],['Per pujar al pis de dalt fem servir l’___.','escala'],['La vaca ens dona ___.','llet'],
['El vaixell navega pel ___.','mar'],['Guardem la roba dins de l’___.','armari'],['La persona que apaga incendis és el ___.','bomber'],['Per escoltar música fem servir els ___.','auriculars'],['Una setmana té set ___.','dies'],
['El contrari de ràpid és ___.','lent'],['Els arbres perden les fulles a la ___.','tardor'],['La capital de Catalunya és ___.','barcelona'],['La cadira serveix per ___.','seure'],['El gos mou la cua quan està ___.','content'],
['Les abelles viuen en un ___.','rusc'],['La biblioteca és plena de ___.','llibres'],['El timbre sona quan algú truca a la ___.','porta'],['La lluna gira al voltant de la ___.','terra'],['El cuiner prepara el menjar a la ___.','cuina'],
['Per respirar necessitem ___.','aire'],['La taronja té molta vitamina ___.','c'],['El diumenge ve després del ___.','dissabte'],['La persona que condueix un autobús és el ___.','conductor'],['Quan fa fred podem encendre la ___.','calefacció'],
['Un triangle té tres ___.','costats'],['El conill té les orelles molt ___.','llargues'],['La brúixola indica el ___.','nord'],['Per fer una foto utilitzem una ___.','càmera'],['El jardiner rega les ___.','plantes']
];

const words=`aigua aire ala alba amic amor ample antic arbre arena armari art avi avia avui baix bala banc banda bar barca barri bassa basto blau boca bosc bota braç branca breu bruixa buit cabra cada cadira caixa cala cama cami camp canço cap cara carta casa cavall cel cendra cent centre cera ciutat clar classe clau col color conte cor corda cos costa cotxe creu cuina culpa dau dia dolç dona dos dret dur escola estiu estrella facil familia fang far farina festa foc font fort fred fruita fulla fum gat gel gerra gir gola gol gos gran grau grup guerra gust herba home hora hort hotel idea illa joc jove juliol juny llac llar llet lletra llibre llit llop llum mà màgia maig mal mare mar massa matí mel mes mestre metro mica mig mirall món muntanya música nas nen net neu nit nom nord nou número obra ocell oli ona orella ou pa padrí pare parc part pas pedra pell peix pera petit plaça plat platja ple pluja poble pont porta prat preu punt quatre ràdio ram rei riu roca roda rosa ruta sac sal salt sang sec senyal set seu sol sopa sorra sud suc taula te teatre temps terra tieta tigre títol tomàquet torre tren tres tro tros ull un vaca vall vaixell vent verd vi vida vila vint viu veu zona abella abric acord actor agulla alegria alumne animal any arròs avio balco ball barret bicicleta blanc bomber bossa braçalet cabell cafè camell camisa camió campana capsa caramel carrer castell catorze cercle cinema ciutat completa conill corall correr cosi crema dissabte dema dibuix diumenge dormir drac dutxa entrada equip escala escombra espelma esquena estació estany estel família finestra flor formatge gall gallina gana garatge gatet gelat germà guitarra habitació història hivern hospital jardí joguina jugador llapis llarg llengua lleó lleuger llimona maduixa maleta mapa mariner mercat mirador motxilla motor natura nevera núvol ocella panera paper paraula paret patata pati pilota pintura piscina planeta planta plàtan ploma plorar poema poble pregunta primavera primer quatre regal rellotge resposta sabata sabó samarreta setmana silenci somriure tarda tardor tassa teulada tisora tovallola treball tren ullera vacança vaixell valent vermell viatge xocolata xiulet zebra aeroport auricular biblioteca bicicleta calefacció càmera carretera col·legi conductor costat cullera escola església estrelles farmàcia finestra formatgeria galliner habitació helicòpter llibretes llargues ordinador paraigua pàgines pastisseria plantes porteria prestatgeria setmana telèfon temperatura universitat`;

window.MB_DATA={culture:culture.map(([question,options,answer])=>({question,options,answer})),phrases:phrases.map(([sentence,answer])=>({sentence,answer})),words:[...new Set(words.toLocaleLowerCase('ca').split(/\s+/).filter(word=>word.length>=2&&word.length<=11))]};
})();
