const {emptyBoard,buildBag,draw,validateMove,applyMove}=require('./word-game');
const rooms=new Map();
const GAMES=new Set(['cultura','lletres','quadrat','sudoku','emparaulats']);
const LEVELS=new Set(['easy','normal','hard']);
function send(socket,payload){if(socket?.readyState===1)socket.send(JSON.stringify(payload))}
function cleanName(value){return String(value||'').trim().slice(0,20)||'Jugador'}
function cleanGame(value){return GAMES.has(value)?value:'sudoku'}
function cleanLevel(value){return LEVELS.has(value)?value:'normal'}
function makeCode(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let code;do code=Array.from({length:5},()=>chars[Math.floor(Math.random()*chars.length)]).join('');while(rooms.has(code));return code}
function dateKey(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Madrid'}).format(new Date())}
function hash(text){let value=2166136261;for(const char of String(text)){value^=char.charCodeAt(0);value=Math.imul(value,16777619)}return value>>>0}
function rng(seed){let value=hash(seed)||1;return()=>{value+=0x6D2B79F5;let t=value;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function maxPlayers(room){return room.game==='emparaulats'?2:5}
function publicPlayers(room){return room.players.map(player=>({id:player.id,name:player.name,connected:player.socket?.readyState===1,score:player.score||0,progress:player.progress||0,total:player.total||0,done:Boolean(player.done)}))}
function broadcast(room,payload){room.players.forEach(player=>send(player.socket,payload))}
function state(room){broadcast(room,{type:'arcade_state',roomCode:room.code,game:room.game,difficulty:room.difficulty,phase:room.phase,creatorId:room.players[0]?.id||null,players:publicPlayers(room),maxPlayers:maxPlayers(room)})}
function leaveCurrent(socket,notify=true){const room=rooms.get(socket.arcadeRoomCode);if(!room)return;const index=room.players.findIndex(player=>player.id===socket.playerId);if(index<0)return;const [player]=room.players.splice(index,1);clearTimeout(player.disconnectTimer);socket.arcadeRoomCode=null;if(!room.players.length){rooms.delete(room.code);return}if(room.phase!=='lobby'){room.phase='lobby';room.word=null;room.players.forEach(value=>{value.score=0;value.progress=0;value.done=false})}if(notify)broadcast(room,{type:'arcade_player_left'});state(room)}
function create(socket,message){leaveCurrent(socket,false);const game=cleanGame(message.game),player={id:socket.playerId,name:cleanName(message.playerName),socket,score:0,progress:0,total:0,done:false};const room={code:makeCode(),game,difficulty:cleanLevel(message.difficulty),phase:'lobby',players:[player],startedAt:0,word:null};rooms.set(room.code,room);socket.arcadeRoomCode=room.code;send(socket,{type:'arcade_created',roomCode:room.code});state(room)}
function join(socket,message){leaveCurrent(socket,false);const code=String(message.roomCode||'').trim().toUpperCase(),room=rooms.get(code);if(!room)return send(socket,{type:'error',message:'La sala no existeix.'});if(room.players.length>=maxPlayers(room))return send(socket,{type:'error',message:'La sala ja és plena.'});if(room.phase!=='lobby')return send(socket,{type:'error',message:'La partida ja ha començat.'});room.players.push({id:socket.playerId,name:cleanName(message.playerName),socket,score:0,progress:0,total:0,done:false});socket.arcadeRoomCode=code;send(socket,{type:'arcade_joined',roomCode:code});state(room)}
function resume(socket,message){const room=rooms.get(String(message.roomCode||'').toUpperCase()),player=room?.players.find(value=>value.id===message.playerId);if(!room||!player)return send(socket,{type:'arcade_resume_failed'});clearTimeout(player.disconnectTimer);player.disconnectTimer=null;player.socket=socket;socket.playerId=player.id;socket.arcadeRoomCode=room.code;send(socket,{type:'arcade_resumed',playerId:player.id,roomCode:room.code,phase:room.phase});if(room.word)sendWordStates(room);else{state(room);if(room.phase==='playing')send(socket,{type:'arcade_challenge_started',seed:room.seed,game:room.game,difficulty:room.difficulty,startedAt:room.startedAt})}}
function start(socket){const room=rooms.get(socket.arcadeRoomCode);if(!room||room.players[0]?.id!==socket.playerId||room.players.length<2||room.phase!=='lobby')return;room.players.forEach(player=>{player.score=0;player.progress=0;player.total=0;player.done=false});room.startedAt=Date.now();room.phase='playing';room.seed=`${dateKey()}-${room.game}-${room.difficulty}`;if(room.game==='emparaulats')startWord(room,room.seed);else broadcast(room,{type:'arcade_challenge_started',seed:room.seed,game:room.game,difficulty:room.difficulty,startedAt:room.startedAt})}
function progress(socket,message){const room=rooms.get(socket.arcadeRoomCode),player=room?.players.find(value=>value.id===socket.playerId);if(!room||!player||room.phase!=='playing'||room.game==='emparaulats')return;player.progress=Math.max(0,Math.min(100,Number(message.done)||0));player.total=Math.max(0,Math.min(100,Number(message.total)||0));player.score=Math.max(0,Math.min(50000,Math.round(Number(message.score)||0)));broadcast(room,{type:'arcade_progress_state',players:publicPlayers(room)})}
function submit(socket,message){const room=rooms.get(socket.arcadeRoomCode),player=room?.players.find(value=>value.id===socket.playerId);if(!room||!player||room.phase!=='playing'||room.game==='emparaulats'||player.done)return;player.score=Math.max(0,Math.min(50000,Math.round(Number(message.score)||0)));player.elapsedMs=Math.max(0,Math.min(7200000,Math.round(Number(message.elapsedMs)||Date.now()-room.startedAt)));player.done=true;broadcast(room,{type:'arcade_progress_state',players:publicPlayers(room)});if(room.players.every(value=>value.done))finishChallenge(room)}
function finishChallenge(room){room.phase='results';const values=publicPlayers(room).map(value=>({...value,elapsedMs:room.players.find(player=>player.id===value.id)?.elapsedMs||0}));broadcast(room,{type:'arcade_results',players:values})}
function startWord(room,seed){const random=rng(seed),bag=buildBag(random);room.word={board:emptyBoard(),bag,turn:0,round:0,passes:0,racks:new Map(),random};room.players.forEach(player=>{room.word.racks.set(player.id,draw(bag,7));player.score=0});sendWordStates(room)}
function sendWordStates(room){const word=room.word;if(!word)return;room.players.forEach(player=>send(player.socket,{type:'arcade_word_state',roomCode:room.code,difficulty:room.difficulty,board:word.board,rack:word.racks.get(player.id)||[],turnId:room.players[word.turn]?.id||null,bagCount:word.bag.length,round:word.round,players:publicPlayers(room)}))}
function wordMove(socket,message){const room=rooms.get(socket.arcadeRoomCode),word=room?.word,player=room?.players[word?.turn];if(!room||!word||player?.id!==socket.playerId)return send(socket,{type:'arcade_word_error',message:'Ara no és el teu torn.'});const rack=word.racks.get(player.id)||[],placements=Array.isArray(message.placements)?message.placements.slice(0,7):[],used=new Set();for(const p of placements){const index=Number(p.rackIndex);if(!Number.isInteger(index)||index<0||index>=rack.length||used.has(index)||rack[index]!==String(p.letter||'').toUpperCase())return send(socket,{type:'arcade_word_error',message:'Les fitxes enviades no coincideixen amb el teu faristol.'});used.add(index)}const result=validateMove(word.board,placements);if(!result.ok)return send(socket,{type:'arcade_word_error',message:result.message});word.board=applyMove(word.board,result.placements);[...used].sort((a,b)=>b-a).forEach(index=>rack.splice(index,1));rack.push(...draw(word.bag,7-rack.length));player.score+=result.score;word.passes=0;advanceWord(room)}
function wordPass(socket){const room=rooms.get(socket.arcadeRoomCode),word=room?.word,player=room?.players[word?.turn];if(!room||!word||player?.id!==socket.playerId)return;const old=word.racks.get(player.id)||[],replacement=draw(word.bag,Math.min(7,word.bag.length));word.bag.push(...old);for(let i=word.bag.length-1;i>0;i--){const j=Math.floor(word.random()*(i+1));[word.bag[i],word.bag[j]]=[word.bag[j],word.bag[i]]}word.racks.set(player.id,replacement);word.passes++;advanceWord(room)}
function advanceWord(room){const word=room.word;word.round++;word.turn=(word.turn+1)%room.players.length;if(word.round>=room.players.length*8||word.passes>=room.players.length*2||(!word.bag.length&&room.players.some(player=>!(word.racks.get(player.id)||[]).length)))return finishWord(room);sendWordStates(room)}
function finishWord(room){room.phase='results';const players=publicPlayers(room).map(value=>({...value,elapsedMs:Date.now()-room.startedAt,done:true}));broadcast(room,{type:'arcade_results',players});room.word=null}
function disconnect(socket){const room=rooms.get(socket.arcadeRoomCode),player=room?.players.find(value=>value.id===socket.playerId);if(!room||!player||player.socket!==socket)return;player.socket=null;clearTimeout(player.disconnectTimer);player.disconnectTimer=setTimeout(()=>leaveById(room,player.id),25000);if(room.word)sendWordStates(room);else state(room)}
function leaveById(room,id){const player=room.players.find(value=>value.id===id);if(!player)return;const fake={playerId:id,arcadeRoomCode:room.code};leaveCurrent(fake,true)}
function handle(socket,message){if(!String(message.type||'').startsWith('arcade_'))return false;switch(message.type){case'arcade_create':create(socket,message);break;case'arcade_join':join(socket,message);break;case'arcade_resume':resume(socket,message);break;case'arcade_start':start(socket);break;case'arcade_progress':progress(socket,message);break;case'arcade_submit':submit(socket,message);break;case'arcade_word_move':wordMove(socket,message);break;case'arcade_word_pass':wordPass(socket);break;case'arcade_leave':leaveCurrent(socket,true);send(socket,{type:'arcade_left'});break;default:send(socket,{type:'error',message:'Ordre de joc desconeguda.'})}return true}
module.exports={handle,disconnect};
